### ISSUE TITLE
Cuda driver error

### ISSUE THREAD

**Issue by rodart** [LeavesBreathe/Seq2Seq_Upgrade_TensorFlow#1]
Hi! Thanks for this module, very helpful stuff is here. I tried to use rnn_cell_enhanced and seq2seq_enhanced for computing my seq2seq model on few GPUs. However I got this error when tried to run code with this imports (rnn_cell_enhanced and seq2seq_enhanced)

I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 32
F tensorflow/stream_executor/cuda/cuda_driver.cc:287] current context was not created by the StreamExecutor cuda_driver API: 0x28c3080; a CUDA runtime call was likely performed without using a StreamExecutor context

I use instance with few Tesla K80 and cuda drivers from tensorflow setup recommendation. Could you help to fix this problem?

**Comment by LeavesBreathe** [comment]
Hey @rodart , I think I've seen this error before not on seq2seq enhanced, but on another separate thing in tensorflow. Try searching their forums for this error. Have you tried running your code on a single tesla k80? try running it on a single one first to make sure it works. 

In addition try searching your error message within tensroflow's group. I have some memory of seeing someone else report that error there. I don't know what it means sorry!

**Comment by LeavesBreathe** [comment]
Also I forgot...try running tensorflow's regular translate example that they give. Make sure it runs on one gpu first. Then try it on the multiple gpu config. That way you can narrow down the problem.

**Comment by rodart** [comment]
Thanks, It was fixed after updating tensorflow lib.
